build-mirror: add mirror fallback like scripts/get_archive
Signed-off-by: Ian Leonard <antonlacon@gmail.com>

diff --git a/tools/build-mirror b/tools/build-mirror
--- a/tools/build-mirror
+++ b/tools/build-mirror
@@ -65,6 +65,7 @@ fi
 while read -r line; do
   PKG_NAME=$(echo "${line}" | cut -d" " -f1 | cut -d":" -f1)
   PKG_URL=$(echo "${line}" | cut -d" " -f2)
+  PKG_FALLBACK=$(echo "${line}" | cut -d" " -f3)
   PKG_FILENAME=$(basename "${PKG_URL}")
   if [ ! -d "${OUTPUT_DIR}/${PKG_NAME}" ]; then
     mkdir -p "${OUTPUT_DIR}/${PKG_NAME}"
@@ -75,6 +76,15 @@ while read -r line; do
     else
       VERBOSE_OPTS="--silent --show-error"
     fi
-    curl --progress-bar ${VERBOSE_OPTS} --fail --connect-timeout 30 --retry 3 --continue-at - --location --max-redirs 5 --output-dir "${OUTPUT_DIR}/${PKG_NAME}/" --output "${PKG_FILENAME}" "${PKG_URL}"
+    curl --progress-bar ${VERBOSE_OPTS} --fail --connect-timeout 30 --retry 3 --continue-at - --location --max-redirs 5 --output-dir "${OUTPUT_DIR}/${PKG_NAME}/" --output "${PKG_FILENAME}" "${PKG_URL}" || echo "ERROR: Failed to download ${PKG_NAME}. Trying fallback..."
+    # try distro's mirror as fallback
+    if [ ! -f "${OUTPUT_DIR}/${PKG_NAME}/${PKG_FILENAME}" ]; then
+      if [ "${VERBOSE}" = "true" ]; then
+        echo "Downloading: ${PKG_NAME} from ${PKG_URL}"
+      else
+        VERBOSE_OPTS="--silent --show-error"
+      fi
+      curl --progress-bar ${VERBOSE_OPTS} --fail --connect-timeout 30 --retry 3 --continue-at - --location --max-redirs 5 --output-dir "${OUTPUT_DIR}/${PKG_NAME}/" --output "${PKG_FILENAME}" "${PKG_FALLBACK}" || echo "ERROR: ${PKG_NAME} failed to download. Moving to next package..."
+    fi
   fi
 done < "${INPUT_FILE:-/dev/stdin}"
